# Generated by Django 4.1.2 on 2023-01-13 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Makanan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(default=None, max_length=50)),
                ('harga', models.CharField(default=None, max_length=50)),
                ('gambar', models.ImageField(default=None, upload_to='static/img/')),
            ],
        ),
    ]
