# Generated by Django 4.1.2 on 2023-01-13 12:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pesanan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jumlah', models.IntegerField(default=1)),
                ('makanan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='menu.makanan')),
            ],
        ),
    ]
