# Generated by Django 4.1.2 on 2023-01-15 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0003_alter_makanan_harga'),
    ]

    operations = [
        migrations.AlterField(
            model_name='makanan',
            name='harga',
            field=models.IntegerField(default=None),
        ),
    ]
